// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
  defaultSidebar: [
    'index',
    { type: 'autogenerated', dirName: '02-getting-started' },
    {
      type: 'category',
      label: 'CI Platforms',
      collapsed: false,
      items: [
        { type: 'autogenerated', dirName: '03-github' },
        { type: 'autogenerated', dirName: '05-gitlab' },
        { type: 'autogenerated', dirName: '11-circleci' },
        { type: 'autogenerated', dirName: '12-self-hosting' },
      ],
    },
    { type: 'autogenerated', dirName: '03-github-cli' },
    { type: 'autogenerated', dirName: '03-github-orchestrator' },
    { type: 'autogenerated', dirName: '08-docker' },
    { type: 'autogenerated', dirName: '09-troubleshooting' },
    { type: 'autogenerated', dirName: '10-faq' },
  ],
};
